version: "3.9"
services:
  yolov8_train:
    container_name: yolov8_train
    build:
      context: .
      dockerfile: x86.dockerfile
    ipc: host
    deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]
    volumes:
      - ../training:/app/training   # training output
      - ../data/640x256/yolo:/app/data  # training data
      - ./2023-07-19.yaml:/app/config/dataset.yaml  # dataset settings
      - ./2023-07-19_hyp.yaml:/app/config/hyp.yaml  # customized hyperparameters
    command: >
      python /repos/LMI_AI_Solutions/object_detectors/yolov8_lmi/cmd.py
