[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "object_detectors"
version = "0.0.0"
description = "LMI AI Solutions object detectors"

[tool.setuptools]
packages = ["ultralytics_lmi", "yolov8_lmi", "core", "detectron2_lmi"]