version: "3.9"
services:
  generate_trt:
    build:
      context: .
      dockerfile: ./$DOCKER_FILE
    volumes:
      - $WEIGHT_PATH:/app/weight.pt
      - $CONFIG_PATH:/app/config.yaml
      - ./trt_engines/:/app/trt_engines/
      - ./build_engine.sh:/app/build_engine.sh
    env_file:
      - ./.env
    deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]
    command: bash /app/build_engine.sh && sleep 1000
    # stdin_open: true # docker run -i
    # tty: true        # docker run -t
