version: "3.3"
services:
  generate_trt:
    build:
      context: .
      dockerfile: ./dockerfile.$PLATFORM
    volumes:
      - $WEIGHT_PATH:/app/weight.pt
      - $CONFIG_PATH:/app/config.yaml
      - ./trt_engines/:/app/trt_engines/
      - ./build_engine.sh:/app/build_engine.sh
    env_file:
      - ./.env
    runtime: nvidia
    deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]
    command: bash -c "export CUDA_CUDART_LIBRARY=/usr/local/cuda/lib64/stubs
      && CUDA_CUDART_LIBRARY=/usr/local/cuda/lib64/stubs cmake /app/tensorrtx/yolov5 && CUDA_CUDART_LIBRARY=/usr/local/cuda/lib64/stubs make
      && sleep 1000 && /app/build_engine.sh"
    # stdin_open: true # docker run -i
    # tty: true        # docker run -t
