[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "anomaly_detectors"
version = "0.0.0"
description = "LMI AI Solutions anomaly detectors"

[tool.setuptools]
packages = ["anomalib_lmi", "core"]