version: "3.9"
services:
  objdet_generate_trt:
    build:
      context: .
      dockerfile: ./dockerfile
    volumes:
      - ./.vscode:/app/.vscode
      - ./sample_files/trained-inference-models:/app/trained-inference-models
      - ./sample_files/data:/app/data
      - ./trt_objdet.py:/app/trt_objdet.py
      - ./requirements.txt:/app/requirements.txt
      - ./export_saved_model.sh:/app/export_saved_model.sh
      - ./generate_trt.sh:/app/generate_trt.sh
      - ./savedmodel_withbuild.py:/app/savedmodel_withbuild.py
    deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]
    # command: ./generate_trt.sh
    stdin_open: true # docker run -i
    tty: true        # docker run -t
