[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "classifiers"
version = "0.0.0"
description = "LMI AI Solutions classifiers"


[tool.setuptools]
packages = ["ultralytics_lmi", "yolov8_lmi", "core", "detectron2_lmi"]